### ISSUE TITLE
Video?

### ISSUE THREAD

**Issue by PeteBoucher** [adafruit/Pi_Internet_Thing_Videos#1]
This looks like a great project to web enable the Pi based weather station I'm building with my kids! Can you include a link to the video tutorial please?

**Comment by toddtreece** [comment]
added the first video to the readme with 5c359f18d2d8a358bfb9efbb562b0ac119b16b04

thanks for the suggestion, and here's the link:
https://www.youtube.com/watch?v=L55QYFnnrgo
